# Generated by Django 4.2.11 on 2026-05-21 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertlog',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_logs', to='api.building'),
        ),
        migrations.AddField(
            model_name='useralertconfirmation',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_alert_confirmations', to='api.building'),
        ),
    ]
